# Generated by Django 4.2.7 on 2026-04-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=120, unique=True)),
                ('current_price_per_sq_ft', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('number_of_listings', models.PositiveIntegerField()),
                ('upcoming_infrastructure', models.BooleanField(default=False)),
                ('distance_from_metro', models.DecimalField(decimal_places=2, max_digits=6)),
                ('growth_score', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('growth_category', models.CharField(choices=[('high', 'High Growth'), ('medium', 'Medium Growth'), ('low', 'Low Growth')], default='low', editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-growth_score', 'area_name'],
            },
        ),
    ]
